services:
  ehrqc-env:
    build: 
      context: ./ehrqc
    image: ehrqc:latest
    volumes:
      - ./ehrqc/data:/home/EHRQC/data
    depends_on:
      - db
      - vocab
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
    image: ehrqc-backend
    restart: always
    depends_on:
      - ehrqc-env
    ports:
      - "5001:5001"
    stdin_open: true
    tty: true
  
  frontend:
    build:
        context: ./frontend
    image: ehrqc-frontend
    restart: always
    ports:
      - "3000:80"  # Map nginx port 80 to localhost:3000
    stdin_open: true
    tty: true

  db:
    image: postgres
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    command: -p 5434
  
  vocab:
    build:
      context: ./vocabulary
    image: ehrqc-vocab
    stdin_open: true
    tty: true
    depends_on:
      - ehrqc-env